server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newtable?useUnicode=true&autoReconnect=true&useSSL=false
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
  mvc:
    static-path-pattern: /**
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yk.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true